logging:
  level:
    ROOT: INFO

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  #datasource:
  #  type: com.zaxxer.hikari.HikariDataSource
  #  hikari:
  #    poolName: Hikari
  #    auto-commit: false
  #  driverClassName: org.postgresql.Driver
  #  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  #  username: ${DB_USERNAME}
  #  password: ${DB_PASSWORD}

github:
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PASSWORD}
