apiVersion: v1
kind: Service
metadata:
  name:  devops-backend-service
  namespace: ${NAMESPACE_NAME}
spec:
  type: NodePort
  selector:
    app: devops-backend
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000