apiVersion: v1
kind: Service
metadata:
  name:  devops-backend-service
  namespace: <NAMESPACE_NAME>
spec:
  type: LoadBalancer
  selector:
    app: devops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
